### PR TITLE
fix postinstall hook

### LINKED ISSUE #1: `postinstall` should use npm run instead of yarn
`"postinstall": "yarn cache:init"` 
This hook will run after the package is installed. It doesn't work if someone have not installed `yarn`.

I think we should use a more "common use" way for most user. Everyone have `npm`.

1. Please use use `npm run` instead of `yarn` in this hook.
2. Move `mkdirp` to dependencies because it is used after global installed.

### PR DESCRIPTION
**Pull request by viko16**
fixed #1

### CODE REVIEW

**Comment by JordanAdams** [comment]
Cheers for this 🎉

**Comment by JordanAdams** [comment]
@viko16 Would you like to be added to the `authors` section of the `package.json`? :)

**Comment by viko16** [comment]
No, I’m good. 
Thank you @JordanAdams . 😄

**Comment by JordanAdams** [comment]
🚀 Published in `v0.1.3`

**Pull request merged**
